### ISSUE TITLE
Question: should non-default/included themes be excluded from git?

### ISSUE THREAD

**Issue by cameronterry** [svandragt/lamb#82]
After following the setup instructions, I created a new theme called `[root]/src/themes/custom-theme-test`. I noticed that the files within `custom-theme-test` were showing up in source control.

Is this the expected behaviour? (Perhaps only an issue if you `git clone` rather than export Lamb ...)

My thinking is, I'd probably be inclined to move my custom theme into it's own repository separate from Lamb itself. This way I can version control my customisations independently of Lamb updates.

If not, then I think a modification to the `.gitignore` file that could be appropriate would be something like the following.

```
# Ignore custom themes by default
/src/themes/
!/src/themes/2024
!/src/themes/default
```

Essentially version control any default/included themes, and ignore the rest.

**Comment by svandragt** [comment]
Yeah good idea. I confirm that checking out a git repo inside the themes folder still makes the lamb project think there are new files.
